import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import * as XLSX from 'xlsx';
import { AlertTriangle, BarChart3, ChevronLeft, ChevronRight, Download, Droplets, Eye, FileSpreadsheet, Pencil, Plus, Search, Smartphone, Trash2, Wifi, X, Zap } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { api } from '@/lib/api';
import { useApp } from '@/lib/AppContext';
import { Branch, ConsumptionRecord, MONTHS, money, number, sum, totalMoney } from '@/lib/consumptions';

type FormData = Omit<ConsumptionRecord,'id'|'branchCode'|'branchName'>;
const emptyForm = (branches:Branch[]):FormData => ({branchId:branches[0]?.id||null,year:new Date().getFullYear(),month:new Date().getMonth()+1,electricityAmount:null,electricityKwh:null,waterAmount:null,waterM3:null,telecomInternetFixedAmount:null,telecomMobileAmount:null,notes:null});
const COLORS=['#f59e0b','#3b82f6','#8b5cf6','#ec4899'];
const val=(v:unknown)=>v===''||v===null||v===undefined||v==='-'?null:Number(v);

export function Consumptions(){
 const {currentUser}=useApp(); const admin=currentUser?.role==='Administrateur'; const canEdit=Boolean(currentUser); const canExport=admin||['Direction','Manager'].includes(String(currentUser?.role));
 const [rows,setRows]=useState<ConsumptionRecord[]>([]),[branches,setBranches]=useState<Branch[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [year,setYear]=useState('Tous'),[month,setMonth]=useState('Tous'),[branch,setBranch]=useState('Toutes'),[type,setType]=useState('Tous'),[search,setSearch]=useState('');
 const [page,setPage]=useState(1),[sort,setSort]=useState<'date'|'branch'|'total'>('date'),[asc,setAsc]=useState(false),[compareMode,setCompareMode]=useState('Total dépenses');
 const [formOpen,setFormOpen]=useState(false),[form,setForm]=useState<FormData>(emptyForm([])),[editId,setEditId]=useState<number|null>(null),[view,setView]=useState<ConsumptionRecord|null>(null);
 const [importOpen,setImportOpen]=useState(false),[preview,setPreview]=useState<any[]>([]),[importInfo,setImportInfo]=useState({valid:0,incomplete:0,errors:0});
 const load=async()=>{try{const [r,b]=await Promise.all([api.get<ConsumptionRecord[]>('/consumptions/records'),api.get<Branch[]>('/consumptions/branches')]);setRows(r);setBranches(b)}catch(e){setError(e instanceof Error?e.message:'Chargement impossible')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const years=useMemo(()=>[...new Set(rows.map(r=>r.year))].sort((a,b)=>b-a),[rows]);
 const filtered=useMemo(()=>rows.filter(r=>(year==='Tous'||r.year===+year)&&(month==='Tous'||r.month===+month)&&(branch==='Toutes'||r.branchCode===branch)&&(type==='Tous'||(type==='Électricité'&&(r.electricityAmount!=null||r.electricityKwh!=null))||(type==='Eau'&&(r.waterAmount!=null||r.waterM3!=null))||(type==='Internet/Fixe'&&r.telecomInternetFixedAmount!=null)||(type==='Mobile'&&r.telecomMobileAmount!=null))),[rows,year,month,branch,type]);
 const displayed=useMemo(()=>filtered.filter(r=>`${r.year} ${MONTHS[r.month-1]} ${r.branchCode||'Global'}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>{let d=sort==='branch'?String(a.branchCode).localeCompare(String(b.branchCode)):sort==='total'?totalMoney(a)-totalMoney(b):(a.year*12+a.month)-(b.year*12+b.month);return asc?d:-d}),[filtered,search,sort,asc]);
 const branchRows=filtered.filter(r=>r.branchId!==null), total=filtered.reduce((a,r)=>a+totalMoney(r),0), uniquePeriods=new Set(filtered.map(r=>`${r.year}-${r.month}`)).size||1;
 const previous=useMemo(()=>{if(year==='Tous'||month==='Tous')return[];let y=+year,m=+month-1;if(!m){m=12;y--}return rows.filter(r=>r.year===y&&r.month===m&&(branch==='Toutes'||r.branchCode===branch))},[rows,year,month,branch]);
 const evolution=(current:number,key:keyof ConsumptionRecord)=>{const p=sum(previous,key);return p?((current-p)/p)*100:null};
 const monthly=useMemo(()=>{const base=year==='Tous'?filtered:rows.filter(r=>r.year===+year&&(branch==='Toutes'||r.branchCode===branch));return MONTHS.map((name,i)=>{const x=base.filter(r=>r.month===i+1);return{name:name.slice(0,3),electricity:sum(x,'electricityAmount'),water:sum(x,'waterAmount'),internet:sum(x,'telecomInternetFixedAmount'),mobile:sum(x,'telecomMobileAmount')}})},[rows,filtered,year,branch]);
 const byBranch=branches.map(b=>{const x=filtered.filter(r=>r.branchId===b.id);return{name:b.code,total:x.reduce((a,r)=>a+totalMoney(r),0),electricity:sum(x,'electricityAmount'),water:sum(x,'waterAmount'),telecom:sum(x,'telecomInternetFixedAmount')+sum(x,'telecomMobileAmount')}});
 const physical=(key:keyof ConsumptionRecord)=>MONTHS.map((name,i)=>{const o:any={name:name.slice(0,3)};branches.forEach(b=>o[b.code]=sum(filtered.filter(r=>r.month===i+1&&r.branchId===b.id),key));return o});
 const pie=[{name:'Électricité',value:sum(filtered,'electricityAmount')},{name:'Eau',value:sum(filtered,'waterAmount')},{name:'Internet/Fixe',value:sum(filtered,'telecomInternetFixedAmount')},{name:'Mobile',value:sum(filtered,'telecomMobileAmount')}].filter(x=>x.value>0);
 const anomalies=useMemo(()=>rows.filter(r=>r.branchId).flatMap(r=>{const prior=rows.filter(p=>p.branchId===r.branchId&&(p.year*12+p.month)<(r.year*12+r.month)).sort((a,b)=>(b.year*12+b.month)-(a.year*12+a.month)).slice(0,3);if(prior.length<3)return[];const checks:[keyof ConsumptionRecord,string][]=[['electricityAmount','montant électrique'],['electricityKwh','consommation électrique'],['waterAmount','montant eau'],['waterM3','consommation eau']];return checks.flatMap(([key,label])=>{const avg=sum(prior,key)/3,c=r[key] as number|null;return c!=null&&avg>0&&c>avg*1.2?[{...r,label,value:c,avg,variation:(c-avg)/avg*100}]:[]})}).slice(0,8),[rows]);
 const comparison=useMemo(()=>{const y=year==='Tous'?(years[0]||new Date().getFullYear()):+year;const keys:[keyof ConsumptionRecord,string][]=[['electricityAmount','Électricité MAD'],['electricityKwh','Électricité kWh'],['waterAmount','Eau MAD'],['waterM3','Eau m³'],['telecomInternetFixedAmount','Internet/Fixe'],['telecomMobileAmount','Mobile']];return{year:y,items:keys.map(([key,label])=>{const cur=sum(rows.filter(r=>r.year===y),key),prev=sum(rows.filter(r=>r.year===y-1),key);return{label,cur,prev,pct:prev?(cur-prev)/prev*100:null}})}} ,[rows,year,years]);
 const openAdd=()=>{setForm(emptyForm(branches));setEditId(null);setFormOpen(true)}; const openEdit=(r:ConsumptionRecord)=>{setForm({...r});setEditId(r.id);setFormOpen(true)};
 const save=async(e:React.FormEvent)=>{e.preventDefault();try{editId?await api.put(`/consumptions/records/${editId}`,form):await api.post('/consumptions/records',form);setFormOpen(false);await load()}catch(e){setError(e instanceof Error?e.message:'Enregistrement impossible')}};
 const remove=async(id:number)=>{if(!confirm('Êtes-vous sûr de vouloir supprimer cette consommation ?'))return;await api.delete(`/consumptions/records/${id}`);await load()};
 const exportData=(kind:'csv'|'xlsx')=>{const data=displayed.map(r=>({'Année':r.year,'Mois':MONTHS[r.month-1],'Branche':r.branchCode||'Global','Électricité MAD':r.electricityAmount,'Électricité kWh':r.electricityKwh,'Eau MAD':r.waterAmount,'Eau m³':r.waterM3,'Internet/Fixe MAD':r.telecomInternetFixedAmount,'Mobile MAD':r.telecomMobileAmount,'Total MAD':totalMoney(r)}));const ws=XLSX.utils.json_to_sheet(data);if(kind==='xlsx'){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Consommations');XLSX.writeFile(wb,'consommations.xlsx')}else{const blob=new Blob([XLSX.utils.sheet_to_csv(ws)],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='consommations.csv';a.click();URL.revokeObjectURL(a.href)}};
 const readExcel=async(file:File)=>{const wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),sheet=wb.Sheets[wb.SheetNames[0]],data:any[][]=XLSX.utils.sheet_to_json(sheet,{header:1,raw:true,defval:null});let y:number|null=null,m:number|null=null;const names:any={janvier:1,'février':2,fevrier:2,mars:3,avril:4,mai:5,juin:6,juillet:7,'août':8,aout:8,septembre:9,octobre:10,novembre:11,'décembre':12,decembre:12};const combine=(...v:unknown[])=>v.every(x=>val(x)===null)?null:v.reduce<number>((a,x)=>a+(val(x)||0),0);const out:any[]=[];for(const row of data){if(Number(row[0])>=2000)y=+row[0];const mn=names[String(row[1]||'').trim().toLowerCase()];if(mn)m=mn;const code=String(row[2]||'').trim().toUpperCase();if(y&&m&&['G1','G2','G3','G5'].includes(code))out.push({year:y,month:m,branchCode:code,electricityAmount:val(row[3]),electricityKwh:val(row[4]),waterAmount:combine(row[6],row[8]),waterM3:combine(row[7],row[9]),telecomInternetFixedAmount:null,telecomMobileAmount:null});if(y&&m&&(row[11]!=null||row[12]!=null))out.push({year:y,month:m,branchCode:'GLOBAL',electricityAmount:null,electricityKwh:null,waterAmount:null,waterM3:null,telecomInternetFixedAmount:val(row[11]),telecomMobileAmount:val(row[12])})}const valid=out.filter(r=>Object.keys(r).some(k=>!['year','month','branchCode'].includes(k)&&r[k]!=null));setPreview(valid);setImportInfo({valid:valid.length,incomplete:valid.filter(r=>Object.values(r).some(v=>v===null)).length,errors:out.length-valid.length});setImportOpen(true)};
 const validateImport=async()=>{await api.post('/consumptions/import',{records:preview});setImportOpen(false);setPreview([]);await load()};
 const pageSize=12,pages=Math.max(1,Math.ceil(displayed.length/pageSize)),paged=displayed.slice((page-1)*pageSize,page*pageSize);
 return <div className="space-y-6 pb-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">Pilotage des charges</p><h1 className="mt-1 text-2xl font-bold text-slate-950">Suivi des Consommations</h1><p className="mt-1 text-sm text-slate-500">Dépenses, consommations physiques et tendances par branche.</p></div><div className="flex flex-wrap gap-2">{admin&&<label className="action secondary"><FileSpreadsheet className="h-4 w-4"/>Importer Excel<input type="file" accept=".xlsx,.xls" hidden onChange={e=>e.target.files?.[0]&&readExcel(e.target.files[0])}/></label>}{canEdit&&<button className="action primary" onClick={openAdd}><Plus className="h-4 w-4"/>Ajouter une consommation</button>}</div></div>
 <div className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:grid-cols-2 xl:grid-cols-4"><Filter label="Année" value={year} set={v=>{setYear(v);setPage(1)}} options={['Tous',...years.map(String)]}/><Filter label="Mois" value={month} set={v=>{setMonth(v);setPage(1)}} options={['Tous',...MONTHS.map((x,i)=>`${i+1}|${x}`)]}/><Filter label="Branche" value={branch} set={v=>{setBranch(v);setPage(1)}} options={['Toutes',...branches.map(b=>b.code)]}/><Filter label="Type" value={type} set={v=>setType(v)} options={['Tous','Électricité','Eau','Internet/Fixe','Mobile']}/></div>
 {error&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}{loading?<Skeleton/>:<><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><Kpi title="Dépense totale" value={money(total)} icon={BarChart3} color="blue"/><Kpi title="Électricité" value={money(sum(filtered,'electricityAmount'))} sub={`${number(sum(filtered,'electricityKwh'))} kWh`} trend={evolution(sum(filtered,'electricityAmount'),'electricityAmount')} icon={Zap} color="amber"/><Kpi title="Eau" value={money(sum(filtered,'waterAmount'))} sub={`${number(sum(filtered,'waterM3'))} m³`} trend={evolution(sum(filtered,'waterAmount'),'waterAmount')} icon={Droplets} color="cyan"/><Kpi title="Maroc Telecom" value={money(sum(filtered,'telecomInternetFixedAmount')+sum(filtered,'telecomMobileAmount'))} sub={`Fixe ${money(sum(filtered,'telecomInternetFixedAmount'))} · Mobile ${money(sum(filtered,'telecomMobileAmount'))}`} icon={Wifi} color="violet"/><Kpi title="Moyenne / branche" value={money(branchRows.length?branchRows.reduce((a,r)=>a+totalMoney(r),0)/(new Set(branchRows.map(r=>r.branchId)).size||1)/uniquePeriods:0)} sub="Moyenne mensuelle" icon={BarChart3} color="slate"/></div>
 <div className="grid gap-5 xl:grid-cols-2"><Chart title="Évolution mensuelle des dépenses"><ResponsiveContainer><LineChart data={monthly}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis/><Tooltip formatter={v=>money(Number(v))}/><Legend/><Line dataKey="electricity" name="Électricité" stroke="#f59e0b" strokeWidth={2}/><Line dataKey="water" name="Eau" stroke="#3b82f6" strokeWidth={2}/><Line dataKey="internet" name="Internet/Fixe" stroke="#8b5cf6" strokeWidth={2}/><Line dataKey="mobile" name="Mobile" stroke="#ec4899" strokeWidth={2}/></LineChart></ResponsiveContainer></Chart><Chart title="Comparaison des branches" action={<select value={compareMode} onChange={e=>setCompareMode(e.target.value)} className="select-mini"><option>Total dépenses</option><option>Électricité</option><option>Eau</option><option>Telecom</option></select>}><ResponsiveContainer><BarChart data={byBranch}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis/><Tooltip formatter={v=>money(Number(v))}/><Bar dataKey={compareMode==='Électricité'?'electricity':compareMode==='Eau'?'water':compareMode==='Telecom'?'telecom':'total'} fill="#2563eb" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></Chart><Chart title="Consommation électrique (kWh)"><ResponsiveContainer><LineChart data={physical('electricityKwh')}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis/><Tooltip/><Legend/>{branches.map((b,i)=><Line key={b.id} dataKey={b.code} stroke={COLORS[i%COLORS.length]} strokeWidth={2}/>)}</LineChart></ResponsiveContainer></Chart><Chart title="Consommation d’eau (m³)"><ResponsiveContainer><LineChart data={physical('waterM3')}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis/><Tooltip/><Legend/>{branches.map((b,i)=><Line key={b.id} dataKey={b.code} stroke={COLORS[i%COLORS.length]} strokeWidth={2}/>)}</LineChart></ResponsiveContainer></Chart><Chart title="Répartition des dépenses"><ResponsiveContainer><PieChart><Pie data={pie} dataKey="value" nameKey="name" innerRadius={65} outerRadius={105} paddingAngle={3}>{pie.map((_,i)=><Cell key={i} fill={COLORS[i]}/>)}</Pie><Tooltip formatter={v=>money(Number(v))}/><Legend/></PieChart></ResponsiveContainer></Chart><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-900">Comparaison {comparison.year} / {comparison.year-1}</h2><div className="mt-3 space-y-2">{comparison.items.map(x=><div key={x.label} className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2 text-sm"><span>{x.label}</span><span className="font-semibold">{number(x.prev)} → {number(x.cur)} <b className={x.pct!=null&&x.pct>=0?'text-red-600':'text-emerald-600'}>{x.pct==null?'—':`${x.pct>=0?'+':''}${x.pct.toFixed(1)}%`}</b></span></div>)}</div></div></div>
 {anomalies.length>0&&<div className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="flex items-center gap-2 font-bold text-amber-900"><AlertTriangle className="h-5 w-5"/>Anomalies détectées (+20 %)</h2><div className="mt-3 grid gap-2 md:grid-cols-2">{anomalies.map((a,i)=><div key={i} className="rounded-xl bg-white p-3 text-sm"><b>{a.label} élevée — {a.branchCode}</b><p className="text-slate-600">{MONTHS[a.month-1]} {a.year} : {number(a.value)} · moyenne 3 mois : {number(a.avg)} · <span className="text-red-600">+{a.variation.toFixed(1)}%</span></p></div>)}</div></div>}
 <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 p-4"><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input className="field pl-9" placeholder="Rechercher…" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></div><div className="flex gap-2">{canExport&&<button className="action secondary" onClick={()=>exportData('csv')}><Download className="h-4 w-4"/>CSV</button>}{canExport&&<button className="action secondary" onClick={()=>exportData('xlsx')}><Download className="h-4 w-4"/>Excel</button>}<select className="select-mini" value={sort} onChange={e=>setSort(e.target.value as any)}><option value="date">Date</option><option value="branch">Branche</option><option value="total">Total</option></select><button className="action secondary" onClick={()=>setAsc(!asc)}>{asc?'↑':'↓'}</button></div></div><div className="overflow-x-auto"><table className="w-full min-w-[1250px] text-sm"><thead><tr>{['Année','Mois','Branche','Électricité MAD','Électricité kWh','Eau MAD','Eau m³','Internet/Fixe','Mobile','Total MAD','Actions'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{paged.map(r=><tr key={r.id} onClick={()=>setView(r)} className="cursor-pointer"><td>{r.year}</td><td>{MONTHS[r.month-1]}</td><td>{r.branchCode?<Link onClick={e=>e.stopPropagation()} className="font-bold text-blue-600" to={`/consommations/branches/${r.branchCode}`}>{r.branchCode}</Link>:'Global'}</td>{(['electricityAmount','electricityKwh','waterAmount','waterM3','telecomInternetFixedAmount','telecomMobileAmount'] as const).map(k=><td key={k}>{r[k]==null?'—':k.includes('Amount')?money(r[k]!):number(r[k]!)}</td>)}<td className="font-bold">{money(totalMoney(r))}</td><td><div className="flex gap-1"><button title="Voir" onClick={e=>{e.stopPropagation();setView(r)}}><Eye/></button>{canEdit&&<button title="Modifier" onClick={e=>{e.stopPropagation();openEdit(r)}}><Pencil/></button>}{admin&&<button title="Supprimer" onClick={e=>{e.stopPropagation();remove(r.id)}}><Trash2/></button>}</div></td></tr>)}{!paged.length&&<tr><td colSpan={11} className="py-12 text-center text-slate-400">Aucune consommation trouvée.</td></tr>}</tbody></table></div><div className="flex items-center justify-between border-t p-4 text-sm"><span>{displayed.length} ligne(s)</span><div className="flex items-center gap-2"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}><ChevronLeft/></button><span>{page} / {pages}</span><button disabled={page===pages} onClick={()=>setPage(p=>p+1)}><ChevronRight/></button></div></div></div></>}
 {formOpen&&<Modal close={()=>setFormOpen(false)} title={editId?'Modifier la consommation':'Ajouter une consommation'}><form onSubmit={save} className="grid gap-4 sm:grid-cols-2"><SelectField label="Branche" value={String(form.branchId??'')} set={v=>setForm({...form,branchId:+v})} options={branches.map(b=>`${b.id}|${b.code}`)}/><Field label="Année" value={form.year} set={v=>setForm({...form,year:+v})} type="number"/><SelectField label="Mois" value={String(form.month)} set={v=>setForm({...form,month:+v})} options={MONTHS.map((x,i)=>`${i+1}|${x}`)}/><div/><Section name="Électricité"/><Num label="Montant MAD" k="electricityAmount" form={form} set={setForm}/><Num label="Consommation kWh" k="electricityKwh" form={form} set={setForm}/><Section name="Eau"/><Num label="Montant MAD" k="waterAmount" form={form} set={setForm}/><Num label="Consommation m³" k="waterM3" form={form} set={setForm}/><Section name="Maroc Telecom"/><Num label="Internet / Fixe MAD" k="telecomInternetFixedAmount" form={form} set={setForm}/><Num label="Mobile MAD" k="telecomMobileAmount" form={form} set={setForm}/><label className="sm:col-span-2 text-sm font-semibold">Notes<textarea className="field mt-1 w-full" value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="action primary sm:col-span-2 justify-center">Enregistrer</button></form></Modal>}
 {view&&<Modal close={()=>setView(null)} title={`${view.branchCode||'Global'} · ${MONTHS[view.month-1]} ${view.year}`}><div className="grid gap-3 sm:grid-cols-2">{[['Électricité',view.electricityAmount==null?'—':money(view.electricityAmount)],['Consommation électrique',view.electricityKwh==null?'—':`${number(view.electricityKwh)} kWh`],['Eau',view.waterAmount==null?'—':money(view.waterAmount)],['Consommation eau',view.waterM3==null?'—':`${number(view.waterM3)} m³`],['Internet/Fixe',view.telecomInternetFixedAmount==null?'—':money(view.telecomInternetFixedAmount)],['Mobile',view.telecomMobileAmount==null?'—':money(view.telecomMobileAmount)],['Total',money(totalMoney(view))]].map(([a,b])=><div className="rounded-xl bg-slate-50 p-3" key={a}><p className="text-xs text-slate-500">{a}</p><p className="font-bold">{b}</p></div>)}</div></Modal>}
 {importOpen&&<Modal close={()=>setImportOpen(false)} title="Aperçu de l’import Excel"><div className="grid grid-cols-3 gap-3"><Stat n={importInfo.valid} t="lignes valides"/><Stat n={importInfo.incomplete} t="données incomplètes"/><Stat n={importInfo.errors} t="erreurs"/></div><div className="mt-4 max-h-72 overflow-auto rounded-xl border"><table className="w-full text-sm"><thead><tr><th>Année</th><th>Mois</th><th>Branche</th><th>Électricité</th><th>Eau</th></tr></thead><tbody>{preview.slice(0,30).map((r,i)=><tr key={i}><td>{r.year}</td><td>{MONTHS[r.month-1]}</td><td>{r.branchCode}</td><td>{r.electricityAmount??'—'}</td><td>{r.waterAmount??'—'}</td></tr>)}</tbody></table></div><button onClick={validateImport} className="action primary mt-4 w-full justify-center">Valider l’import ({preview.length} lignes)</button></Modal>}
 </div>
}

function Filter({label,value,set,options}:{label:string,value:string,set:(v:string)=>void,options:string[]}){return <label className="text-xs font-bold text-slate-500">{label}<select className="field mt-1 w-full" value={value} onChange={e=>set(e.target.value)}>{options.map(o=>{const [v,l]=o.includes('|')?o.split('|'):[o,o];return <option value={v} key={v}>{l}</option>})}</select></label>}
function Kpi({title,value,sub,trend,icon:Icon,color}:{title:string,value:string,sub?:string,trend?:number|null,icon:any,color:string}){const tones:Record<string,string>={blue:'bg-blue-50 text-blue-600',amber:'bg-amber-50 text-amber-600',cyan:'bg-cyan-50 text-cyan-600',violet:'bg-violet-50 text-violet-600',slate:'bg-slate-100 text-slate-600'};return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><div className={`rounded-xl p-2.5 ${tones[color]}`}><Icon className="h-5 w-5"/></div><p className="text-xs font-bold uppercase text-slate-400">{title}</p></div><p className="mt-3 text-xl font-bold text-slate-950">{value}</p>{sub&&<p className="mt-1 text-xs text-slate-500">{sub}</p>}{trend!=null&&<p className={`mt-1 text-xs font-bold ${trend>=0?'text-red-600':'text-emerald-600'}`}>{trend>=0?'+':''}{trend.toFixed(1)} % vs mois précédent</p>}</div>}
function Chart({title,children,action}:{title:string,children:React.ReactNode,action?:React.ReactNode}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold text-slate-900">{title}</h2>{action}</div><div className="h-72">{children}</div></div>}
function Modal({title,close,children}:{title:string,close:()=>void,children:React.ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div className="max-h-[92dvh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white shadow-2xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b bg-white p-5"><h2 className="font-bold">{title}</h2><button onClick={close}><X/></button></div><div className="p-5">{children}</div></div></div>}
function Field({label,value,set,type='text'}:{label:string,value:any,set:(v:string)=>void,type?:string}){return <label className="text-sm font-semibold">{label}<input className="field mt-1 w-full" type={type} value={value??''} onChange={e=>set(e.target.value)}/></label>}
function SelectField({label,value,set,options}:{label:string,value:string,set:(v:string)=>void,options:string[]}){return <label className="text-sm font-semibold">{label}<select className="field mt-1 w-full" value={value} onChange={e=>set(e.target.value)}>{options.map(o=>{const [v,l]=o.split('|');return <option value={v} key={v}>{l}</option>})}</select></label>}
function Num({label,k,form,set}:{label:string,k:keyof FormData,form:FormData,set:React.Dispatch<React.SetStateAction<FormData>>}){return <Field label={label} type="number" value={form[k]} set={v=>set({...form,[k]:v===''?null:+v})}/>}function Section({name}:{name:string}){return <h3 className="sm:col-span-2 border-b pb-2 font-bold text-blue-700">{name}</h3>}function Stat({n,t}:{n:number,t:string}){return <div className="rounded-xl bg-slate-50 p-3 text-center"><b className="text-xl">{n}</b><p className="text-xs text-slate-500">{t}</p></div>}function Skeleton(){return <div className="grid gap-4 md:grid-cols-4">{[1,2,3,4].map(i=><div key={i} className="h-32 animate-pulse rounded-2xl bg-slate-200"/>)}</div>}
